name: Run Tests

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Install GIMP
        run: |
          sudo apt install flatpak
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y flathub org.gimp.GIMP
      - name: Install xcftools
        run: |
          sudo apt install xcftools
      - name: Setup Python
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Generate
        run: |
          mkdir tests
          python -m xcftestsuite generate tests
      - name: Test
        run: |
          python -m xcftestsuite test tests
      - name: Report
        run: |
          python -m xcftestsuite report tests
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'tests/.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
